"use client"

import { useState, useEffect } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { aonaAPI } from "@/lib/api-client"
import { InkBrushDivider } from "@/components/ink-brush-divider"

export default function AlertsPage() {
  const [agentData, setAgentData] = useState<any>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function fetchAlerts() {
      try {
        const data = await aonaAPI.getAgentOutput()
        setAgentData(data)
        setLoading(false)
      } catch (error) {
        console.error('Failed to fetch agent data:', error)
        setLoading(false)
      }
    }
    fetchAlerts()
    const interval = setInterval(fetchAlerts, 30000)
    return () => clearInterval(interval)
  }, [])

  const allAlerts = agentData?.nodes
    ?.flatMap((n: any) => n.alerts?.map((a: any) => ({...a, nodeId: n.nodeId, nodeName: n.nodeName})) || []) || []

  const criticalAlerts = allAlerts.filter((a: any) => a.severity === 'critical')
  const warningAlerts = allAlerts.filter((a: any) => a.severity === 'warning')
  const infoAlerts = allAlerts.filter((a: any) => a.severity === 'info')

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'critical':
        return 'border-red-500/50 bg-red-500/10 text-red-500'
      case 'warning':
        return 'border-yellow-500/50 bg-yellow-500/10 text-yellow-500'
      default:
        return 'border-blue-500/50 bg-blue-500/10 text-blue-500'
    }
  }

  return (
    <div className="min-h-screen bg-background pt-20">
      {/* Header */}
      <div className="container mx-auto px-6 py-12">
        <div className="max-w-3xl">
          <h1 className="text-5xl font-light tracking-widest text-foreground mb-6">
            Water Quality Alerts
          </h1>
          <p className="text-lg font-light text-muted-foreground leading-relaxed tracking-wide">
            Real-time alerts generated by the autonomous AI agent monitoring water quality across the network.
            Alerts are based on EPA water quality standards and environmental context.
          </p>
        </div>
      </div>

      <InkBrushDivider />

      <div className="container mx-auto px-6 py-8 space-y-8">
        {/* Stats */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          <Card className="border-border/50 bg-card/50 backdrop-blur-sm">
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-light text-muted-foreground">Total Alerts</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-4xl font-light">{allAlerts.length}</div>
            </CardContent>
          </Card>
          <Card className="border-border/50 bg-red-500/5">
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-light text-muted-foreground">Critical</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-4xl font-light text-red-500">{criticalAlerts.length}</div>
            </CardContent>
          </Card>
          <Card className="border-border/50 bg-yellow-500/5">
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-light text-muted-foreground">Warning</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-4xl font-light text-yellow-500">{warningAlerts.length}</div>
            </CardContent>
          </Card>
          <Card className="border-border/50 bg-blue-500/5">
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-light text-muted-foreground">Info</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-4xl font-light text-blue-500">{infoAlerts.length}</div>
            </CardContent>
          </Card>
        </div>

        {loading && (
          <Card className="border-border/50 bg-card/50 backdrop-blur-sm">
            <CardContent className="py-12 text-center">
              <p className="text-lg font-light text-muted-foreground">Loading alerts...</p>
            </CardContent>
          </Card>
        )}

        {!loading && allAlerts.length === 0 && (
          <Card className="border-border/50 bg-card/50 backdrop-blur-sm">
            <CardContent className="py-12 text-center">
              <p className="text-xl mb-4 font-light">No alerts yet</p>
              <p className="text-sm text-muted-foreground mb-6 font-light">
                Run the autonomous agent to generate water quality alerts:
              </p>
              <code className="px-4 py-2 bg-muted rounded text-sm">npm run agent</code>
              <div className="mt-4 flex justify-center gap-2">
                <Badge variant="outline" className="text-xs">🤖 AI-Powered</Badge>
                <Badge variant="outline" className="text-xs">EPA Standards</Badge>
                <Badge variant="outline" className="text-xs">Real-time</Badge>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Alerts List */}
        {!loading && allAlerts.length > 0 && (
          <div className="space-y-4">
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-2xl font-light tracking-widest text-foreground">Active Alerts</h2>
              <div className="flex gap-2">
                <Badge variant="outline" className="text-xs">🤖 AI-Generated</Badge>
                <Badge variant="outline" className="text-xs border-green-500/50 text-green-500">🔴 LIVE</Badge>
              </div>
            </div>

            {allAlerts.map((alert: any, i: number) => (
              <Card key={i} className={`border-border/50 ${getSeverityColor(alert.severity)}`}>
                <CardHeader>
                  <CardTitle className="flex items-center justify-between text-lg font-light">
                    <span>{alert.nodeName || alert.nodeId.slice(0, 8)}</span>
                    <Badge variant="outline" className={`text-xs ${getSeverityColor(alert.severity)}`}>
                      {alert.severity?.toUpperCase() || 'INFO'}
                    </Badge>
                  </CardTitle>
                  <p className="text-xs text-muted-foreground font-light">
                    {alert.type} · {alert.metric}
                  </p>
                </CardHeader>
                <CardContent>
                  <p className="text-base mb-4 font-light">{alert.message}</p>
                  <div className="flex justify-between items-center text-sm font-light">
                    <div className="space-y-1">
                      <p className="text-muted-foreground">
                        <span className="font-normal">Value:</span> {alert.value}
                      </p>
                      {alert.recommendation && (
                        <p className="text-muted-foreground">
                          <span className="font-normal">Recommendation:</span> {alert.recommendation}
                        </p>
                      )}
                    </div>
                    {alert.timestamp && (
                      <p className="text-xs text-muted-foreground">
                        {new Date(alert.timestamp).toLocaleString()}
                      </p>
                    )}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}

        {/* Agent Summary */}
        {agentData && (
          <Card className="border-border/50 bg-gradient-to-r from-blue-500/5 to-purple-500/5 border-blue-500/20">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg font-light tracking-wide">
                🤖 Agent Analysis Summary
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="mb-4 text-sm font-light text-muted-foreground">
                {agentData.summary?.overallWaterQuality && (
                  <span>Overall Water Quality: <strong className="text-foreground">{agentData.summary.overallWaterQuality}</strong></span>
                )}
              </p>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                <div>
                  <p className="text-muted-foreground font-light">Nodes Consulted:</p>
                  <p className="text-foreground font-normal">{agentData.nodesConsulted || 0}</p>
                </div>
                <div>
                  <p className="text-muted-foreground font-light">Total Spent:</p>
                  <p className="text-foreground font-normal">{agentData.totalSpent?.toFixed(3) || 0} SOL</p>
                </div>
                <div>
                  <p className="text-muted-foreground font-light">Alerts Generated:</p>
                  <p className="text-foreground font-normal">{agentData.alertsGenerated || 0}</p>
                </div>
                <div>
                  <p className="text-muted-foreground font-light">Last Run:</p>
                  <p className="text-foreground font-normal">
                    {agentData.timestamp ? new Date(agentData.timestamp).toLocaleTimeString() : 'N/A'}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  )
}
